services:
  postgres:
    image: postgres:18-alpine
    container_name: url_s_db
    restart: unless-stopped
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - url_shortener_data:/var/lib/postgresql/data

volumes:
  url_shortener_data: