services:
  postgres:
    image: postgres:18-alpine
    container_name: url_s_db
    restart: unless-stopped
    ports:
      - ${PG_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-1234}
      POSTGRES_DB: ${PG_DB:-url_db}
    volumes:
      - url_shortener_data:/var/lib/postgresql/data

volumes:
  url_shortener_data: